export const carsData = [
	{
		id: 1,
		title: "Model S",
		description: "Order Online For Touchless Delivery",
		backgroundImg: "model-s.jpg",
		leftBtnText: "Custom Order",
		rightBtnText: "Existing Inventory",
		ref: null,
	},
	{
		id: 2,
		title: "Model Y",
		description: "Order Online For Touchless Delivery",
		backgroundImg: "model-y.jpg",
		leftBtnText: "Custom Order",
		rightBtnText: "Existing Inventory",
		ref: null,
	},
	{
		id: 3,
		title: "Model X",
		description: "Order Online For Touchless Delivery",
		backgroundImg: "model-x.jpg",
		leftBtnText: "Custom Order",
		rightBtnText: "Existing Inventory",
		ref: null,
	},
	{
		id: 4,
		title: "Model 3",
		description: "Order Online For Touchless Delivery",
		backgroundImg: "model-3.jpg",
		leftBtnText: "Custom Order",
		rightBtnText: "Existing Inventory",
		ref: null,
	},
];
